#!/usr/bin/env node
// Writes the non-secret build module that carries the build commit into the Function as the
// API version, with the application environment (spec §3 and §7). Pages compiles Functions after
// the build command, so `build:pages` runs this before exporting the client.
const fs = require('node:fs');
const path = require('node:path');

const { publicValuesAt } = require('./scan-dist');

const ENVIRONMENTS = ['development', 'staging', 'production'];
const COMMIT_SHA = /^[0-9a-f]{40}$/;

// On Cloudflare only the build's own variables count. Locally, the public values Expo inlines
// (the .env files, then the process environment) and the checked-out commit.
function resolveBuildInfo(env, { publicValues, gitHead }) {
  if (env.CF_PAGES === '1') {
    for (const name of ['CF_PAGES_COMMIT_SHA', 'EXPO_PUBLIC_APP_ENV']) {
      if (!env[name]) throw new Error(`${name} is missing from the Cloudflare build.`);
    }
  }
  const version = env.CF_PAGES_COMMIT_SHA ?? gitHead();
  const environment = env.EXPO_PUBLIC_APP_ENV ?? publicValues.EXPO_PUBLIC_APP_ENV;
  if (!COMMIT_SHA.test(version)) {
    throw new Error(`CF_PAGES_COMMIT_SHA (or the checked-out commit) is not a full commit SHA.`);
  }
  if (!ENVIRONMENTS.includes(environment)) {
    throw new Error(`EXPO_PUBLIC_APP_ENV must be one of ${ENVIRONMENTS.join(', ')}.`);
  }
  return { version, environment };
}

function renderModule({ version, environment }) {
  return [
    '// Generated by scripts/build-info.js. Do not edit or commit.',
    `export const version = '${version}';`,
    `export const environment = '${environment}';`,
    '',
  ].join('\n');
}

function main() {
  const { execFileSync } = require('node:child_process');
  const root = path.resolve(__dirname, '..');
  const info = resolveBuildInfo(process.env, {
    publicValues: publicValuesAt(root, process.env),
    gitHead: () =>
      execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim(),
  });
  fs.writeFileSync(path.join(root, 'functions', 'build-info.ts'), renderModule(info));
  console.log(`build-info: API version ${info.version} in ${info.environment}.`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`build-info: ${error.message}`);
    process.exit(1);
  }
}

module.exports = { resolveBuildInfo };
